### ISSUE TITLE
VM Issue: Duplicate un-commented lines in /etc/network/interfaces

### ISSUE THREAD

**Issue by deltasierra** [open-switch/opx-platform-config#30]
The OPX VM, has two lines in the /etc/network/interfaces that should either be removed or commented out.  It's unclear if they were manually added prior to packaging or via some other build process.  

Some network functions, such as "ifreload" fails and returns errors because of these additional lines. 

Lines 3 & 6 below 

> source-directory /etc/network/interfaces.d

**EXAMPLE**:
```
opxUser@opx_vm:~$ cat /etc/network/interfaces 
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
auto eth0
iface eth0 inet dhcp
source-directory /etc/network/interfaces.d
opxUser@opx_vm:~$ 
```

```
opxUser@opx_vm:~$ sudo ifreload -a

> error: /etc/network/interfaces: line3: error processing line 'source-directory /etc/network/interfaces.d'
opxUser@opx_vm:~$ 
```

```
opxUser@opx_vm:~$ opx-show-version 
OS_NAME="OPX"
OS_VERSION="2.1.0"
PLATFORM="S6000-VM"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch blueprint for Dell 1.0.0"
BUILD_VERSION="2.1.0(0)"
BUILD_DATE="2017-08-04T12:01:19-0700"
INSTALL_DATE="2017-09-17T05:28:26+0000"
SYSTEM_UPTIME= 22 minutes
Failed to get D-Bus connection: No such file or directory
SYSTEM_STATE= 
UPGRADED_PACKAGES=no
ALTERED_PACKAGES=no
opxUser@opx_vm:~$ 
```

**Comment by jeff-yin** [comment]
@hpersh will fix this in the upcoming OPX 2.1.1 release.

**Comment by hpersh** [comment]
I did a fresh install of OPX 2.1.0 on a VM.  I do not see this issue.

Is the file "/etc/network/interfaces.d/eth0" present?  What does it contain?  It should contain:

auto eth0
allow-hotplug eth0
iface eth0 inet dhcp

**Comment by jeff-yin** [comment]
@deltasierra are you still running into this issue? if so, can you respond to @hpersh 's question?

**Comment by jeff-yin** [comment]
Closing the issue for now
