### ISSUE TITLE
opx-config-switch show errors 

### ISSUE THREAD

**Issue by deltasierra** [open-switch/opx-platform-config#33]
root@l2:~# opx-config-switch show
Key: 1.36.2359341.
base-switch/switching-entities/switch-count = 1
Key: 1.36.2359341.2359299.2359302.
base-switch/switching-entities/switching-entity/num-unicast-queues-per-port = 10
base-switch/switching-entities/switching-entity/uft-mode = 1
base-switch/switching-entities/switching-entity/lag-hash-algorithm = 2
base-switch/switching-entities/switching-entity/acl-entry-max-priority = 2147483647
base-switch/switching-entities/switching-entity/bridge-table-size = 163840
base-switch/switching-entities/switching-entity/max-ecmp-entry-per-group = 0
base-switch/switching-entities/switching-entity/ecmp-hash-algorithm = 2
base-switch/switching-entities/switching-entity/switch-id = 0
base-switch/switching-entities/switching-entity/acl-table-max-priority = 11
base-switch/switching-entities/switching-entity/acl-table-min-priority = 0
base-switch/switching-entities/switching-entity/max-mtu = 9216
base-switch/switching-entities/switching-entity/acl-entry-min-priority = 0
base-switch/switching-entities/switching-entity/counter-refresh-interval = 5
base-switch/switching-entities/switching-entity/num-queues-per-port = 20
base-switch/switching-entities/switching-entity/total-buffer-size = 12188
base-switch/switching-entities/switching-entity/mac-age-timer = 1800
base-switch/switching-entities/switching-entity/egress-buffer-pool-num = 4
base-switch/switching-entities/switching-entity/num-multicast-queues-per-port = 10
base-switch/switching-entities/switching-entity/default-mac-address = 64:00:6a:e6:f6:14
base-switch/switching-entities/switching-entity/num-queues-cpu-port = 43
`Traceback (most recent call last):
  File "/usr/bin/opx-config-switch", line 55, in <module>
    options[opt](sys.argv[2:])
  File "/usr/bin/opx-config-switch", line 22, in show_switch
    nas_switch_utils.show_switch(args)
  File "/usr/lib/x86_64-linux-gnu/opx/nas_switch_utils.py", line 58, in show_switch
    cps_utils.print_obj(i)
  File "/usr/lib/opx/cps_utils.py", line 293, in print_obj
    cps_attr_types_map.print_object(obj, log=None)
  File "/usr/lib/opx/cps_utils.py", line 187, in print_object
    print_methods[module](data)
  File "/usr/lib/x86_64-linux-gnu/opx/nas_switch_utils.py", line 65, in print_switch_details
    value = cps_object.types.from_data(key,data)
  File "/usr/lib/opx/cps_utils.py", line 148, in from_data
    return bytearray_utils.ba_to_value(t, val)
  File "/usr/lib/opx/bytearray_utils.py", line 259, in ba_to_value
    return ba_to_type[typ](typ, val)
  File "/usr/lib/opx/bytearray_utils.py", line 231, in hex_from_data
    return binascii.hexlify(val)
TypeError: must be string or buffer, not dict`

`root@l2:~# opx-show-version`
`OS_NAME="OPX-Base-Dell"`
`OS_VERSION="2.1.0"`
`PLATFORM=""`
`ARCHITECTURE="x86_64"`
`INTERNAL_BUILD_ID="OpenSwitch Base Blue Print 1.0.0"`
`BUILD_VERSION="2.1.0(26)"`
`BUILD_DATE="2017-07-14T23:29:12+0000"`
`INSTALL_DATE="2017-08-05T16:57:21+0000"`
`SYSTEM_UPTIME= 1 week, 1 day, 7 hours, 9 minutes`
`SYSTEM_STATE= running`
`UPGRADED_PACKAGES=no`
`ALTERED_PACKAGES=no`

**Comment by GarrickHe** [comment]
Hello @deltasierra ,

I root-caused and have a potential fix for this issue. Will let you know when it's pushed into github.

thanks,
Garrick

**Comment by GarrickHe** [comment]
Hello @Ragsboss @deltasierra,
Fix has been pushed into opx-nas-l2:

Fix: traceback seen when using 'opx-config-switch show'.
Change-Id: I0e6de836fcfbcacff9f3a772d2851f9392b284bb
Signed-off-by: Garrick He garrick_he@dell.com

Thank you,
Garrick
