### ISSUE TITLE
Add udev rules for Ethernet interfaces for all Dell specific VM platforms

### ISSUE THREAD

**Issue by mikelazar** [open-switch/opx-platform-config#34]
There should a be a udev rules file in /etc/udev/rules.d to rename standard Ethernet interfaces to e101-00N-0 for all type of Dell VM platforms - not just S6000.

Currently, this file is in: 

opx-platform-config/vendor/dell/s6000-vm/lib/udev/rules.d/80-dn-virt-intf.rules

**Comment by jeff-yin** [comment]
This is resolved and should be available starting in OPX 2.2.0.0-dev
