### ISSUE TITLE
no /usr/bin/opx-vport.sh for S6000-VM

### ISSUE THREAD

**Issue by dkalog** [open-switch/opx-platform-config#35]
Hi  *
 I am trying to establish a working environment with  a VM using the latest vagrant box namely the opx/2.2.0-dev.  Although this is supposed to be an S6000 model there is no  /etc/udev/rules.d/80-dn-virt-intf.rules . When I tried to copy I couldn't find  /usr/bin/opx-vport.sh  which is mentioned inside.   What do you suggest ?

Cheers
Dimitris

**Comment by atanu-mandal** [comment]
Hi @dkalog, sorry for the delayed response, I seemed to have overlooked your observation till this point. There is a fix recently made on this (https://review.openswitch.net/#/c/14510/1/debian/opx-platform-config-dell-vm.install). On your target please copy /usr/bin/bin/opx-vport.sh to /usr/bin/ and reload the VM, that should take care of the issue. Also 80-dn-virt-intf.rules now resides at /lib/udev/rules.d (which is the standard location). FYI, https://github.com/open-switch/opx-platform-config/blob/master/vendor/dell/s6000-vm/bin/opx-vport.sh
Hope that helps.
Thanks,
-Atanu
