### ISSUE TITLE
Missing ACLs for IS-IS packets

### ISSUE THREAD

**Issue by michaelsiuda** [open-switch/opx-platform-config#36]
The default ACLs in /etc/opx/acl/*.xml do not have the rules required to run IS-IS routing protocol.

IS-IS protocol sends L2 packets to these multicast MAC addresses:
- 01:80:c2:00:00:14
- 01:80:c2:00:00:15
- 09:00:2b:00:00:05
 
I've tested that by adding these entries I was able to get IS-IS working on an S6010 switch.

/etc/opx/acl/nas_detail_list.xml 
```
     <entry tag="isis-l1">
         <match type="DST_MAC">
             <value>
                 <addr>01:80:c2:00:00:14</addr>
             </value>
         </match>
     </entry>

     <entry tag="isis-l2">
         <match type="DST_MAC">
             <value>
                 <addr>01:80:c2:00:00:15</addr>
             </value>
         </match>
     </entry>

     <entry tag="isis-all">
         <match type="DST_MAC">
             <value>
                 <addr>09:00:2b:00:00:05</addr>
             </value>
         </match>
     </entry>
```

/etc/opx/acl/nas_master_list.xml
```
            <entry tag="isis-l1"            cpu-q="9"  action="TRAP_TO_CPU"/>
            <entry tag="isis-l2"            cpu-q="9"  action="TRAP_TO_CPU"/>
            <entry tag="isis-all"           cpu-q="9"  action="TRAP_TO_CPU"/>
```

Could these (or similar) be added the default ACLs on all platforms?

Thanks,
Michael

**Comment by atanu-mandal** [comment]
Hi Michael,
Sure. Thanks for trying it out. We will plan to accommodate the changes you have proposed.

Thanks,
-Atanu

**Comment by atanu-mandal** [comment]
This is addressed by
[https://github.com/open-switch/opx-platform-config/pull/47](url)
