### ISSUE TITLE
Adding routes on Dell EMC S4248FB(L)-ON is slow

### ISSUE THREAD

**Issue by hpersh** [open-switch/opx-platform-config#40]
In a scaled BGP environment (32x ECMP with 124,000 routes), reconvergence of the routing table after a link flap event takes significantly longer than on other platforms. 

Suspected root cause is that the default QoS settings for the S4248FB/L platform are throttling control plane packets destined for the CPU.

**Comment by jeff-yin** [comment]
Fixed by https://github.com/open-switch/opx-platform-config/commit/274dbc0b497e4ceb471bdd1cbf6a230c505b3b24 . Will be available in OPX 3.0.0
