### ISSUE TITLE
BGP traffic rate for S4248

### ISSUE THREAD

**Issue by hpersh** [open-switch/opx-platform-config#53]
Adjust QoS parameters to increase rate for BGP traffic

**Comment by hpersh** [comment]
**N.B.  Must be back-ported to OS10**

**Comment by jeff-yin** [comment]
@hpersh is this to _further_ increase the rate for BGP traffic on the S4248, or just to keep track of backporting your _original_ changes to OS10 so that it matches OPX? If the latter, we should just keep track of that internally.
