### ISSUE TITLE
Dell EMC Z9264F - Fail to do interface breakout

### ISSUE THREAD

**Issue by waliulislam** [open-switch/opx-platform-config#69]
Got following TB:

root@OPX:/mnt/onie-boot/admin/3.1.0# opx-config-hybrid-group 
Traceback (most recent call last):
  File "/usr/bin/opx-config-hybrid-group", line 19, in <module>
    import nas_intf_set as nas_if
  File "/usr/bin/nas_intf_set.py", line 61
    intf_name = ether_if_name(port_id, subport_id):
                                                  ^
SyntaxError: invalid syntax
root@OPX:/mnt/onie-boot/admin/3.1.0# opx-config-hybrid-group 
Traceback (most recent call last):
  File "/usr/bin/opx-config-hybrid-group", line 19, in <module>
    import nas_intf_set as nas_if
  File "/usr/bin/nas_intf_set.py", line 61
    intf_name = ether_if_name(port_id, subport_id):
                                                  ^
SyntaxError: invalid syntax
root@OPX:/mnt/onie-boot/admin/3.1.0#

**Comment by nchervela** [comment]
Pull request raised. 
https://github.com/open-switch/opx-nas-interface/pull/68

**Comment by jeff-yin** [comment]
Fix merged. @waliulislam please re-test and close if resolved.

**Comment by waliulislam** [comment]
Verified.
